### ISSUE TITLE
TypeNotFound: Type not found: '(Array, http://schemas.xmlsoap.org/soap/encoding/, )

### ISSUE THREAD

**Issue by kawa-marcin** [unomena/suds#2]
Hello,
I know it was raised multiple times and I've tried to solve this issue by trying things from:
- https://fedorahosted.org/suds/wiki/TipsAndTricks#Schema-TypeNotFound
- https://fedorahosted.org/suds/wiki/Documentation#FIXINGBROKENSCHEMAs
- https://fedorahosted.org/suds/ticket/220

But I am still getting back the error.

The WDSL I am trying to connect to:
-  https://demo.iduws.tracesmart.co.uk/v3.4/?wsdl

Traceback:

``` python
from suds.client import Client
url = 'https://demo.iduws.tracesmart.co.uk/v3.4/?wsdl'
client = Client(url)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/wsdl.py", line 159, in __init__
    self.build_schema()
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/wsdl.py", line 220, in build_schema
    self.schema = container.load(self.options)
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/xsd/schema.py", line 95, in load
    child.dereference()
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/xsd/schema.py", line 323, in dereference
    midx, deps = x.dependencies()
  File "/Users/marcinkawa/Django/initial/dj1.7/lib/python2.7/site-packages/suds/xsd/sxbasic.py", line 259, in dependencies
    raise TypeNotFound(self.ref)
suds.TypeNotFound: Type not found: '(Array, http://schemas.xmlsoap.org/soap/encoding/, )'
```

Any help will be useful.

**Comment by alexdashkov** [comment]
thank you for this solution!
